retrofit.RetrofitError: org.simpleframework.xml.core.ElementException: Element 'span' does not have a match in class jp.ac.tsukuba.cs.coins_p.aid.handyword.communication.jsonschema2pojo.searchDicItem.DicItemTitle at line 11
This error prevents my advance.
How can I solve this problem?
I think it works well if I can set converter to stop converting under <Title> tag.